# Project 1: Analysis of Various Metrics and How They Relate to Stress and Work-Life Balance

## Summary Statistics for Poor, Good, and Excellent Life Balance Scores

In [3]:
# Dependencies
import pandas as pd
import matplotlib.pyplot as plt

## Data Cleaning

In [4]:
# Read csv file
wellbeing_df = pd.read_csv('data/Wellbeing_and_lifestyle_data_Kaggle.csv')
wellbeing_df.head()

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,...,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,7/7/15,3,2,2,5,0,5,2,0,1,...,7,5,5,1,4,0,5,36 to 50,Female,609.5
1,7/7/15,2,3,4,3,8,10,5,2,2,...,8,2,2,2,3,2,6,36 to 50,Female,655.6
2,7/7/15,2,3,3,4,4,10,3,2,2,...,8,10,2,2,4,8,3,36 to 50,Female,631.6
3,7/7/15,3,3,10,3,10,7,2,5,2,...,5,7,5,1,5,2,0,51 or more,Female,622.7
4,7/7/15,5,1,3,3,10,4,2,4,2,...,7,0,0,2,8,1,5,51 or more,Female,663.9

In [5]:
# Change the datatype of the stress column to an integer

# First find the row(s) that is NOT a number on the stress scale
stress_scores = wellbeing_df['DAILY_STRESS'].unique()

# Convert the stress scores into a list
stress_scores_list = list(stress_scores)
print(stress_scores_list)

# From the list, drop the values that are not valid stress scores
invalid_response = '1/1/00'

# Create a variable to filter for the invalid response
drop_response = (wellbeing_df['DAILY_STRESS'] == invalid_response)

# Drop the row containing the invalid response
wellbeing_df = wellbeing_df.loc[~drop_response]
wellbeing_df

# Convert the daily stress column to an integer and check it was converted correctly
wellbeing_df['DAILY_STRESS'] = wellbeing_df['DAILY_STRESS'].astype(int)
wellbeing_df.info()

['2', '3', '1', '4', '5', '0', '1/1/00']
<class 'pandas.core.frame.DataFrame'>
Int64Index: 15971 entries, 0 to 15971
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Timestamp                15971 non-null  object
 1   FRUITS_VEGGIES           15971 non-null  int64
 2   DAILY_STRESS             15971 non-null  int32
 3   PLACES_VISITED           15971 non-null  int64
 4   CORE_CIRCLE              15971 non-null  int64
 5   SUPPORTING_OTHERS        15971 non-null  int64
 6   SOCIAL_NETWORK           15971 non-null  int64
 7   ACHIEVEMENT              15971 non-null  int64
 8   DONATION                 15971 non-null  int64
 9   BMI_RANGE                15971 non-null  int64
 10  TODO_COMPLETED           15971 non-null  int64
 11  FLOW                     15971 non-null  int64
 12  DAILY_STEPS              15971 non-null  int64
 13  LIVE_VISION              15971 non-null  int64
 14  SLEEP_HOURS              15971 non-null  int64
 15  LOST_VACATION            15971 non-null  int64
 16  DAILY_SHOUTING           15971 non-null  int64
 17  SUFFICIENT_INCOME        15971 non-null  int64
 18  PERSONAL_AWARDS          15971 non-null  int64
 19  TIME_FOR_PASSION         15971 non-null  int64
 20  WEEKLY_MEDITATION        15971 non-null  int64
 21  AGE                      15971 non-null  object
 22  GENDER                   15971 non-null  object
 23  WORK_LIFE_BALANCE_SCORE  15971 non-null  float64
dtypes: float64(1), int32(1), int64(19), object(3)
memory usage: 3.0+ MB

## Summary Statistics Tables

In [6]:
# Change settings so all of the rows/columns can be displayed at once
pd.options.display.max_columns = None
pd.options.display.max_rows = None

# Create a dataframe for those who scored in the poor, good, and excellent ranges

poor_score = wellbeing_df[wellbeing_df['WORK_LIFE_BALANCE_SCORE'] < 550]

good_score = wellbeing_df[(wellbeing_df['WORK_LIFE_BALANCE_SCORE'] >= 550) & (wellbeing_df['WORK_LIFE_BALANCE_SCORE'] < 680)]

excellent_score = wellbeing_df[wellbeing_df['WORK_LIFE_BALANCE_SCORE'] > 680]

poor_score.head()

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,FLOW,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
72,7/19/15,0,4,0,2,2,3,1,0,2,1,0,4,0,4,0,10,1,1,0,0,36 to 50,Female,528.8
79,7/20/15,0,5,0,2,0,0,3,0,2,0,1,1,10,6,10,10,1,2,1,10,21 to 35,Male,538.8
82,7/20/15,0,5,0,2,0,0,3,0,2,0,1,1,10,6,10,10,1,2,1,10,21 to 35,Male,538.8
847,9/19/15,1,4,1,1,3,0,0,0,1,6,0,3,0,8,10,10,1,0,0,3,36 to 50,Female,544.7
872,9/22/15,1,4,0,3,2,1,0,0,2,2,0,1,0,4,0,9,1,2,0,3,21 to 35,Female,533.3

In [7]:
# Create a summary for the group that scored poor and save as csv
poor_score_summary = poor_score.groupby('GENDER').agg({'FRUITS_VEGGIES':['mean','median','max','min',],
                                  'DAILY_STRESS':['mean','median','max','min',],
                                  'PLACES_VISITED':['mean','median','max','min',],
                                  'CORE_CIRCLE':['mean','median','max','min',],
                                  'SUPPORTING_OTHERS':['mean','median','max','min',],
                                  'SOCIAL_NETWORK':['mean','median','max','min',],
                                  'ACHIEVEMENT':['mean','median','max','min',],
                                  'DONATION':['mean','median','max','min',],
                                  'BMI_RANGE':['mean','median','max','min',],
                                  'TODO_COMPLETED':['mean','median','max','min',],
                                  'FLOW':['mean','median','max','min',],
                                  'DAILY_STEPS':['mean','median','max','min',],
                                  'LIVE_VISION':['mean','median','max','min',],
                                  'SLEEP_HOURS':['mean','median','max','min',],
                                  'LOST_VACATION':['mean','median','max','min',],
                                  'DAILY_SHOUTING':['mean','median','max','min',],
                                  'SUFFICIENT_INCOME':['mean','median','max','min',],
                                  'PERSONAL_AWARDS':['mean','median','max','min',],
                                  'TIME_FOR_PASSION':['mean','median','max','min',],
                                  'WEEKLY_MEDITATION':['mean','median','max','min',]}).unstack().transpose()
poor_score_summary.to_csv('data/poor_score_summary.csv')
print(poor_score_summary)

                           GENDER
FRUITS_VEGGIES     mean    Female     1.000000
                           Male       0.566667
                   median  Female     1.000000
                           Male       0.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_STRESS       mean    Female     4.477273
                           Male       4.366667
                   median  Female     5.000000
                           Male       5.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
PLACES_VISITED     mean    Female     0.295455
                           Male       0.633333
                   median  Female     0.000000
                           Male       0.000000
                   max     Female     3.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
CORE_CIRCLE        mean    Female     1.568182
                           Male       1.366667
                   median  Female     1.000000
                           Male       1.000000
                   max     Female     8.000000
                           Male       4.000000
                   min     Female     0.000000
                           Male       0.000000
SUPPORTING_OTHERS  mean    Female     1.568182
                           Male       0.433333
                   median  Female     1.000000
                           Male       0.000000
                   max     Female     8.000000
                           Male       3.000000
                   min     Female     0.000000
                           Male       0.000000
SOCIAL_NETWORK     mean    Female     1.840909
                           Male       1.466667
                   median  Female     1.500000
                           Male       1.000000
                   max     Female    10.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
ACHIEVEMENT        mean    Female     0.545455
                           Male       0.666667
                   median  Female     0.000000
                           Male       0.000000
                   max     Female     6.000000
                           Male       3.000000
                   min     Female     0.000000
                           Male       0.000000
DONATION           mean    Female     0.431818
                           Male       0.166667
                   median  Female     0.000000
                           Male       0.000000
                   max     Female     2.000000
                           Male       2.000000
                   min     Female     0.000000
                           Male       0.000000
BMI_RANGE          mean    Female     1.931818
                           Male       1.866667
                   median  Female     2.000000
                           Male       2.000000
                   max     Female     2.000000
                           Male       2.000000
                   min     Female     1.000000
                           Male       1.000000
TODO_COMPLETED     mean    Female     1.522727
                           Male       0.500000
                   median  Female     1.000000
                           Male       0.000000
                   max     Female     6.000000
                           Male       3.000000
                   min     Female     0.000000
                           Male       0.000000
FLOW               mean    Female     0.931818
                           Male       0.566667
                   median  Female     0.500000
                           Male       0.000000
                   max     Female     8.000000
                           Male       3.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_STEPS        mean    Female     2.022727
                           Male       2.166667
                   median  Female     1.000000
                           Male       1.000000
                   max     Female     8.000000
                           Male      10.000000
                   min     Female     1.000000
                           Male       1.000000
LIVE_VISION        mean    Female     0.772727
                           Male       1.500000
                   median  Female     0.000000
                           Male       0.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SLEEP_HOURS        mean    Female     5.477273
                           Male       5.600000
                   median  Female     5.500000
                           Male       6.000000
                   max     Female     9.000000
                           Male      10.000000
                   min     Female     1.000000
                           Male       1.000000
LOST_VACATION      mean    Female     6.477273
                           Male       6.233333
                   median  Female    10.000000
                           Male      10.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_SHOUTING     mean    Female     7.250000
                           Male       7.166667
                   median  Female    10.000000
                           Male      10.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SUFFICIENT_INCOME  mean    Female     1.045455
                           Male       1.100000
                   median  Female     1.000000
                           Male       1.000000
                   max     Female     2.000000
                           Male       2.000000
                   min     Female     1.000000
                           Male       1.000000
PERSONAL_AWARDS    mean    Female     2.022727
                           Male       1.133333
                   median  Female     2.000000
                           Male       1.000000
                   max     Female    10.000000
                           Male       6.000000
                   min     Female     0.000000
                           Male       0.000000
TIME_FOR_PASSION   mean    Female     0.568182
                           Male       0.333333
                   median  Female     0.000000
                           Male       0.000000
                   max     Female     3.000000
                           Male       2.000000
                   min     Female     0.000000
                           Male       0.000000
WEEKLY_MEDITATION  mean    Female     1.545455
                           Male       2.533333
                   median  Female     0.500000
                           Male       1.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
dtype: float64

In [8]:
# Create a summary for the group that scored good 
good_score_summary = good_score.groupby('GENDER').agg({'FRUITS_VEGGIES':['mean','median','max','min',],
                                  'DAILY_STRESS':['mean','median','max','min',],
                                  'PLACES_VISITED':['mean','median','max','min',],
                                  'CORE_CIRCLE':['mean','median','max','min',],
                                  'SUPPORTING_OTHERS':['mean','median','max','min',],
                                  'SOCIAL_NETWORK':['mean','median','max','min',],
                                  'ACHIEVEMENT':['mean','median','max','min',],
                                  'DONATION':['mean','median','max','min',],
                                  'BMI_RANGE':['mean','median','max','min',],
                                  'TODO_COMPLETED':['mean','median','max','min',],
                                  'FLOW':['mean','median','max','min',],
                                  'DAILY_STEPS':['mean','median','max','min',],
                                  'LIVE_VISION':['mean','median','max','min',],
                                  'SLEEP_HOURS':['mean','median','max','min',],
                                  'LOST_VACATION':['mean','median','max','min',],
                                  'DAILY_SHOUTING':['mean','median','max','min',],
                                  'SUFFICIENT_INCOME':['mean','median','max','min',],
                                  'PERSONAL_AWARDS':['mean','median','max','min',],
                                  'TIME_FOR_PASSION':['mean','median','max','min',],
                                  'WEEKLY_MEDITATION':['mean','median','max','min',]}).unstack().transpose()
good_score_summary.to_csv('data/good_score_summary.csv')
print(good_score_summary)

                           GENDER
FRUITS_VEGGIES     mean    Female     2.637961
                           Male       2.339657
                   median  Female     3.000000
                           Male       2.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_STRESS       mean    Female     3.243713
                           Male       2.851910
                   median  Female     3.000000
                           Male       3.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
PLACES_VISITED     mean    Female     4.203066
                           Male       4.019236
                   median  Female     4.000000
                           Male       3.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
CORE_CIRCLE        mean    Female     4.820358
                           Male       4.235310
                   median  Female     4.000000
                           Male       4.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SUPPORTING_OTHERS  mean    Female     4.836548
                           Male       3.891173
                   median  Female     4.000000
                           Male       3.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SOCIAL_NETWORK     mean    Female     5.812780
                           Male       5.520422
                   median  Female     5.000000
                           Male       5.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
ACHIEVEMENT        mean    Female     3.064244
                           Male       2.922530
                   median  Female     3.000000
                           Male       3.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
DONATION           mean    Female     2.354289
                           Male       1.893017
                   median  Female     2.000000
                           Male       1.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
BMI_RANGE          mean    Female     1.491216
                           Male       1.465876
                   median  Female     1.000000
                           Male       1.000000
                   max     Female     2.000000
                           Male       2.000000
                   min     Female     1.000000
                           Male       1.000000
TODO_COMPLETED     mean    Female     5.075095
                           Male       4.601581
                   median  Female     5.000000
                           Male       5.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
FLOW               mean    Female     2.532725
                           Male       2.421871
                   median  Female     2.000000
                           Male       2.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_STEPS        mean    Female     4.830348
                           Male       5.144137
                   median  Female     5.000000
                           Male       5.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     1.000000
                           Male       1.000000
LIVE_VISION        mean    Female     2.682398
                           Male       2.866930
                   median  Female     2.000000
                           Male       2.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SLEEP_HOURS        mean    Female     6.985016
                           Male       6.817918
                   median  Female     7.000000
                           Male       7.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     1.000000
                           Male       1.000000
LOST_VACATION      mean    Female     3.460730
                           Male       3.583136
                   median  Female     2.000000
                           Male       2.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_SHOUTING     mean    Female     3.497244
                           Male       3.037418
                   median  Female     3.000000
                           Male       2.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SUFFICIENT_INCOME  mean    Female     1.617292
                           Male       1.641370
                   median  Female     2.000000
                           Male       2.000000
                   max     Female     2.000000
                           Male       2.000000
                   min     Female     1.000000
                           Male       1.000000
PERSONAL_AWARDS    mean    Female     4.763693
                           Male       4.590777
                   median  Female     4.000000
                           Male       4.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
TIME_FOR_PASSION   mean    Female     2.374440
                           Male       2.464559
                   median  Female     2.000000
                           Male       2.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
WEEKLY_MEDITATION  mean    Female     5.215467
                           Male       5.860343
                   median  Female     5.000000
                           Male       6.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
dtype: float64

In [9]:
# Create a summary for the group that scored good 
excellent_score_summary = excellent_score.groupby('GENDER').agg({'FRUITS_VEGGIES':['mean','median','max','min',],
                                  'DAILY_STRESS':['mean','median','max','min',],
                                  'PLACES_VISITED':['mean','median','max','min',],
                                  'CORE_CIRCLE':['mean','median','max','min',],
                                  'SUPPORTING_OTHERS':['mean','median','max','min',],
                                  'SOCIAL_NETWORK':['mean','median','max','min',],
                                  'ACHIEVEMENT':['mean','median','max','min',],
                                  'DONATION':['mean','median','max','min',],
                                  'BMI_RANGE':['mean','median','max','min',],
                                  'TODO_COMPLETED':['mean','median','max','min',],
                                  'FLOW':['mean','median','max','min',],
                                  'DAILY_STEPS':['mean','median','max','min',],
                                  'LIVE_VISION':['mean','median','max','min',],
                                  'SLEEP_HOURS':['mean','median','max','min',],
                                  'LOST_VACATION':['mean','median','max','min',],
                                  'DAILY_SHOUTING':['mean','median','max','min',],
                                  'SUFFICIENT_INCOME':['mean','median','max','min',],
                                  'PERSONAL_AWARDS':['mean','median','max','min',],
                                  'TIME_FOR_PASSION':['mean','median','max','min',],
                                  'WEEKLY_MEDITATION':['mean','median','max','min',]}).unstack().transpose()
excellent_score_summary.to_csv('data/excellent_score_summary.csv')
print(excellent_score_summary)

                           GENDER
FRUITS_VEGGIES     mean    Female     3.662494
                           Male       3.385055
                   median  Female     4.000000
                           Male       3.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_STRESS       mean    Female     2.438908
                           Male       2.101099
                   median  Female     2.000000
                           Male       2.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
PLACES_VISITED     mean    Female     7.053580
                           Male       6.843077
                   median  Female     8.000000
                           Male       7.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
CORE_CIRCLE        mean    Female     7.086630
                           Male       6.750330
                   median  Female     7.000000
                           Male       7.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SUPPORTING_OTHERS  mean    Female     7.619680
                           Male       7.109451
                   median  Female     8.000000
                           Male       8.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SOCIAL_NETWORK     mean    Female     7.727842
                           Male       7.690110
                   median  Female     9.000000
                           Male       9.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
ACHIEVEMENT        mean    Female     5.398598
                           Male       5.837802
                   median  Female     5.000000
                           Male       5.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
DONATION           mean    Female     3.691788
                           Male       3.370549
                   median  Female     4.000000
                           Male       4.000000
                   max     Female     5.000000
                           Male       5.000000
                   min     Female     0.000000
                           Male       0.000000
BMI_RANGE          mean    Female     1.297947
                           Male       1.294505
                   median  Female     1.000000
                           Male       1.000000
                   max     Female     2.000000
                           Male       2.000000
                   min     Female     1.000000
                           Male       1.000000
TODO_COMPLETED     mean    Female     7.181022
                           Male       6.996044
                   median  Female     8.000000
                           Male       7.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
FLOW               mean    Female     4.260391
                           Male       4.376703
                   median  Female     4.000000
                           Male       4.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_STEPS        mean    Female     6.792188
                           Male       7.036923
                   median  Female     7.000000
                           Male       7.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     1.000000
                           Male       1.000000
LIVE_VISION        mean    Female     5.143716
                           Male       5.599560
                   median  Female     5.000000
                           Male       5.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SLEEP_HOURS        mean    Female     7.278918
                           Male       7.197802
                   median  Female     7.000000
                           Male       7.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     1.000000
                           Male       3.000000
LOST_VACATION      mean    Female     1.854031
                           Male       2.036044
                   median  Female     0.000000
                           Male       0.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
DAILY_SHOUTING     mean    Female     2.397346
                           Male       2.103736
                   median  Female     2.000000
                           Male       1.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
SUFFICIENT_INCOME  mean    Female     1.890085
                           Male       1.898901
                   median  Female     2.000000
                           Male       2.000000
                   max     Female     2.000000
                           Male       2.000000
                   min     Female     1.000000
                           Male       1.000000
PERSONAL_AWARDS    mean    Female     7.210315
                           Male       7.495385
                   median  Female     8.000000
                           Male       8.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
TIME_FOR_PASSION   mean    Female     4.652228
                           Male       4.956044
                   median  Female     4.000000
                           Male       5.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
WEEKLY_MEDITATION  mean    Female     7.253130
                           Male       7.796484
                   median  Female     7.000000
                           Male       8.000000
                   max     Female    10.000000
                           Male      10.000000
                   min     Female     0.000000
                           Male       0.000000
dtype: float64